/// <reference types="../CTAutocomplete" />
/// <reference lib="es2015" />

//huge thanks and credits to: Bonsai, AzuredBlue, Bloom, Ilmars, Aton, Tebey, Turtle and many more ily all <3
import "./stuff/guidk"
import "./features/AutoLeap"
import "./features/PartyCommands"
import "./features/AutoMask"
import "./features/AutoShield"
import "./features/AutoUlt"
import "./features/AutoReady"
import "./features/RelicAura"
import "./features/AutoWish"
import "./features/GuildCommands"
import "./features/CookieClicker"
import "./features/AutoEdrag"
import "./features/ItemMacro"
import "./features/AutoTerminator"
//import "./features/AutoSessionID"
import "./features/GhostBlocks"
import "./features/FlareTimer"
import "./features/VanqNotifier"
import "./features/PowerDisplay"
import "./features/HypeBroken"
import "./features/KuudraAlerts"
import "./features/ESP"
import "./features/dragspawntimer"
import "./features/IHATEDIORITE"
import "./features/AimBot"
import "./features/DragonBox"
import "./features/BlackList"

